version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10

- package-ecosystem: "docker" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "weekly"

# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
